[_NumPy_](https://docs.scipy.org/doc/numpy/reference/) is the basic package for doing slightly more advanced math and storing data in an analytics-friendly form.

Once NumPy is installed we have to import the package into our current environment. This is done with an `import` statement. When importing a package you have the opportunity to set an abbreviation for recalling its functions. Many packages have standard shorthand. The shorthand for `numpy` is simply `np`. You can import and set the abbreviation like this:

In [1]:
import numpy as np

**NOTE** that [Python style](https://www.python.org/dev/peps/pep-0008/#imports) requires they should always appear at the beginning of the script. This allows for easy validation if the necessary packages are installed and keeps track of them in a single place.

### Arrays ###

NumPy array is like a Python list with additional mathematical functionality and properties.  Arrays like lists can have multiple dimensions.  A single dimension works like an ordered set of values, with various points entered in it.  Arrays use bracket notation `[` `]` to acess items by index. Create and array by calling `np.array` and passing in any iterable.

In [2]:
x = np.array([0, 1, 2, 3])
x

array([0, 1, 2, 3])

Remember that you can run and re-run these code cells individually. A good shortcut for running a cell is pressing <kbd>shift</kbd> + <kbd>enter</kbd> from within the cell.

You can add multiple dimensions to your array by either manually creating an array of arrays or with `np.arange()`. Here are two ways to generate the same thing:

In [3]:
w = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
y = np.arange(8).reshape(2, 4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

`np.arange()` ("arange" is short for "array range") works similarly to the basic Python `range()` function by generating a sequence of integers, starting at 0 by default and incrementing by 1. But instead of returning a `range()` object it returns an array. We're taking advantage of that by calling the `.reshape()` [array method](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.reshape.html) to reshape the initial eight-item array into two four-item arrays.

Using `arange()` and `.reshape()`is a common way to create arrays.

### Element-wise and Aggregator functions ###
NumPy's primary value is the ability to do more sophisticated arithmetic than basic Python can do out of the box. NumPy allows you to do these computations in two ways: with *element-wise* functions that process array elements one at a time and then return a new array, and with *aggregator* functions that process the array into a single value the function returns.

In [5]:
x = np.array([0, 1, 2, 3])

# Square each value
print(np.square(x))

# Square root of each value
print(np.sqrt(x))

# Cosine of each value
print(np.cos(x))

[0 1 4 9]
[0.         1.         1.41421356 1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]


Note that these methods return arrays of the same length as the input array, just like the built-in Python function `map()`. Use element-wise functions when you want to transform each individual element in an array and get back a collection of all the results.

Here are some aggregator functions that aggregate the elements of an array and return a single value:

In [6]:
x = np.array([0, 1, 2, 3])

# Find the max value
print(np.max(x))

# Find the mean
print(np.mean(x))

# Find the standard deviation
print(np.std(x))

3
1.5
1.118033988749895


**NOTE** that these aggregator functions return single values, rather than arrays. That is what an **_aggregator_** does. It takes a set of multiple data values and condenses them (or aggregates them) into a single value according to some rule. So `np.min()` returns the minimum value of all the data given to it, `np.mean()` the mean, and so on.

These are some of the basic functions of NumPy, but there are many more. To explore the basic [NumPy documentation](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html).